server:
  port: 9000
  
spring:
  application:
    name: back-apigateway
  cloud:
    gateway:
      routes:
        - id: back-worker
          uri: lb://BACK-WORKER # eureka instance
          predicates:
          - Path=/worker/** # URL
        - id: back-work
          uri: lb://BACK-WORK #eureka instance 
          predicates:
          - Path=/work/** # URL
        - id: back-dashboard
          uri: lb://BACK-DASHBOARD # eureka instance
          predicates:
          - Path=/dashboard/** # URL
      #default-filters:
      #  - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials # 중복 제거
      #globalcors:
      #  cors-configurations:
      #    '[/**]':
      #      allowedOrigins: "*" # 테스트 용도
      #      allowedMethods:
      #      - GET
      #      - POST
      #      - PUT
      #      - DELETE
      #      - OPTIONS
            
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka # 주소 설정
