server:
  port: 9000
  
spring:
  application:
    name: back-apigateway
  cloud:
    gateway:
      routes:
        - id: back-worker
          uri: lb://back-worker/worker
          predicates:
          - Path=/worker/**
        - id: back-work
          uri: lb://back-work/work
          predicates:
          - Path=/work/**
        - id: back-dashboard
          uri: lb://back-dashboard/dashboard
          predicates:
          - Path=/dashboard/**
      #default-filters:
      #  - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials # 중복 제거
      #globalcors:
      #  cors-configurations:
      #    '[/**]':
      #      allowedOrigins: "*" # 테스트 용도
      #      allowedMethods:
      #      - GET
      #      - POST
      #      - PUT
      #      - DELETE
      #      - OPTIONS
            
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka # 주소 설정
